---
- hosts: all
  gather_facts: no
  vars:
    userauthkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    username: <@ username @>

  tasks:
    - debug: var=src_key
    - debug: var=userauthkey
    - debug: var=username
    - name: Add authorized key to "{{ username }}"
      authorized_key: user="{{ username }}" key="{{ userauthkey }}" state=present
