---
- hosts: all
  gather_facts: no
  vars:
    create_username: <@ username @>
    create_hashed_password: <@ new_usr_password | password_hash('sha512') @>

# http://docs.ansible.com/ansible/playbooks_prompts.html
  tasks:
    - debug: msg="Received create_username={{ create_username }}, create_hashed_password={{ create_hashed_password }}"

    - name: Finding the path of bash in /etc/shells (The dflt shell needs to be listed in /etc/shells)
      shell: cat /etc/shells | grep bash | head -n1 || echo '/bin/bash'
      register: bash

    - name: Create user "{{ create_username }}"
      user: name="{{ create_username }}" comment="{{ create_username | capitalize }}" shell="{{ bash.stdout }}" createhome=yes password="{{ create_hashed_password }}" update_password=on_create

    - name: "Generate ssh-key for user {{ create_username }}"
      user: name="{{ create_username }}" generate_ssh_key=yes

    <@@ if is_admin @@>
    - name: "Add user {{ create_username }} to groups"
      user: name="{{ create_username }}" groups=wheel append=yes
    <@@ endif @@>
