---
- hosts: all

  tasks:
    - name: Pinging "{{ ansible_hostname }}"
      ping:

    - name: Get the current user
      shell: echo $USER
      register: myuser

    - name: Print user
      debug: msg="{{ 'Shell gives user as ' + myuser['stdout'] }}"

    - name: Print ansible variables
      debug: var="[ansible_user_id, ansible_hostname, ansible_lsb]"

